apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-deploy 
  minReplicas: 1
  maxReplicas: 4
	# 대상 Object가 이상적으로 가지고 있어야 할 CPU 사용률
	# 대상 Object의 평균 CPU 사용률이 목표 50%에 도달할 수 있는 최적의 Pod 수량 결정/적용
	# 목표 Pod 수 = 현재 Pod 수 X (현재 자원 사용량/목표 자원 사용량) (정수 아닐 시 올림)
  targetCPUUtilizationPercentage: 50