apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
spec:
  serviceAccountName: dashboard-sa
  containers:
  - name: sa-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running!']