# Not Recommended
# You should only create a service account token Secret object if you can't use the TokenRequest API to obtain a token, 
# and the security exposure of persisting a non-expiring token credential in a readable API object is acceptable to you.
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa-token-secret
  annotations:
    kubernetes.io/service-account.name: dashboard-sa