apiVersion: batch/v1
kind: Job
metadata:
  name: cow-say-job-ttlsecondsafterfinished
spec:
  template:
    spec:
      containers:
      - name: cow-say
        image: rancher/cowsay:latest
      restartPolicy: Never
  ttlSecondsAfterFinished: 30