apiVersion: batch/v1
kind: CronJob
metadata:
  name: cow-say-cronjob
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cow-say
            image: rancher/cowsay:latest
          restartPolicy: Never