apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  persistentVolumeReclaimPolicy: Delete
  # persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data