apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: web-contents
  volumes:
    - name: web-contents
      persistentVolumeClaim:
        claimName: pv-claim