apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-app:1.0.0
    env:
    - name: MY_API_KEY
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: my-api-key